apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-fixer.fullname" . }}-migrate
  labels:
    {{- include "k8s-fixer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: {{ include "k8s-fixer.fullname" . }}-config
            - secretRef:
                name: {{ include "k8s-fixer.fullname" . }}-secrets
