"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-06 20:39:52.924328

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('namespace', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('raw_alert', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=True),
    sa.Column('source_message_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    schema='fixer'
    )
    op.create_index('ix_incidents_fingerprint_created', 'incidents', ['fingerprint', 'created_at'], unique=False, schema='fixer')
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False, schema='fixer')
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('root_cause', sa.String(length=2048), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_trace_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['fixer.incidents.id'], name=op.f('fk_diagnoses_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses')),
    schema='fixer'
    )
    op.create_index(op.f('ix_fixer_diagnoses_incident_id'), 'diagnoses', ['incident_id'], unique=False, schema='fixer')
    op.create_table('fix_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('expected_outcome', sa.String(length=2048), nullable=True),
    sa.Column('rollback_hint', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['fixer.incidents.id'], name=op.f('fk_fix_proposals_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fix_proposals')),
    schema='fixer'
    )
    op.create_index(op.f('ix_fixer_fix_proposals_incident_id'), 'fix_proposals', ['incident_id'], unique=False, schema='fixer')
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['fixer.incidents.id'], name=op.f('fk_incident_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events')),
    schema='fixer'
    )
    op.create_index(op.f('ix_fixer_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False, schema='fixer')
    op.create_table('lark_card_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('card_kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['fixer.incidents.id'], name=op.f('fk_lark_card_bindings_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lark_card_bindings')),
    sa.UniqueConstraint('message_id', name=op.f('uq_lark_card_bindings_message_id')),
    schema='fixer'
    )
    op.create_index(op.f('ix_fixer_lark_card_bindings_incident_id'), 'lark_card_bindings', ['incident_id'], unique=False, schema='fixer')
    op.create_table('fix_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['fixer.incidents.id'], name=op.f('fk_fix_executions_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['fixer.fix_proposals.id'], name=op.f('fk_fix_executions_proposal_id_fix_proposals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fix_executions')),
    schema='fixer'
    )
    op.create_index(op.f('ix_fixer_fix_executions_incident_id'), 'fix_executions', ['incident_id'], unique=False, schema='fixer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixer_fix_executions_incident_id'), table_name='fix_executions', schema='fixer')
    op.drop_table('fix_executions', schema='fixer')
    op.drop_index(op.f('ix_fixer_lark_card_bindings_incident_id'), table_name='lark_card_bindings', schema='fixer')
    op.drop_table('lark_card_bindings', schema='fixer')
    op.drop_index(op.f('ix_fixer_incident_events_incident_id'), table_name='incident_events', schema='fixer')
    op.drop_table('incident_events', schema='fixer')
    op.drop_index(op.f('ix_fixer_fix_proposals_incident_id'), table_name='fix_proposals', schema='fixer')
    op.drop_table('fix_proposals', schema='fixer')
    op.drop_index(op.f('ix_fixer_diagnoses_incident_id'), table_name='diagnoses', schema='fixer')
    op.drop_table('diagnoses', schema='fixer')
    op.drop_index('ix_incidents_status', table_name='incidents', schema='fixer')
    op.drop_index('ix_incidents_fingerprint_created', table_name='incidents', schema='fixer')
    op.drop_table('incidents', schema='fixer')
    # ### end Alembic commands ###
